// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.31.1
// source: proto/pickup.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PickupServiceClient is the client API for PickupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PickupServiceClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
}

type pickupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPickupServiceClient(cc grpc.ClientConnInterface) PickupServiceClient {
	return &pickupServiceClient{cc}
}

func (c *pickupServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/pickup.PickupService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PickupServiceServer is the server API for PickupService service.
// All implementations must embed UnimplementedPickupServiceServer
// for forward compatibility
type PickupServiceServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	mustEmbedUnimplementedPickupServiceServer()
}

// UnimplementedPickupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPickupServiceServer struct {
}

func (UnimplementedPickupServiceServer) GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedPickupServiceServer) mustEmbedUnimplementedPickupServiceServer() {}

// UnsafePickupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PickupServiceServer will
// result in compilation errors.
type UnsafePickupServiceServer interface {
	mustEmbedUnimplementedPickupServiceServer()
}

func RegisterPickupServiceServer(s grpc.ServiceRegistrar, srv PickupServiceServer) {
	s.RegisterService(&PickupService_ServiceDesc, srv)
}

func _PickupService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PickupServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pickup.PickupService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PickupServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PickupService_ServiceDesc is the grpc.ServiceDesc for PickupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PickupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pickup.PickupService",
	HandlerType: (*PickupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _PickupService_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pickup.proto",
}
